name: Matix Demo
on: push
jobs:
    build:
        strategy:
            matrix:
                node-version: [12, 14, 16]
                opearting-system: [ubuntu-latest, windows-latest] 
        runs-on: ${{ matrix.opearting-system }}
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Install NodeJS
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
            - name: Install Dependencies
              run: npm ci
            - name: Build project
              run: npm run build        
            

